import type { Metadata } from 'next'
import type { PropsWithChildren } from 'react'

import { Manrope } from 'next/font/google'
import { Toaster } from 'react-hot-toast'

import './globals.css'

const manrope = Manrope({ subsets: ['latin'], weight: ['400', '500', '600'] })

export const metadata: Metadata = {
  title: 'Drink Master',
  description: 'Generated by create next app'
}

// bg-primaryLight text-fs-14-fw-400-lh-1.28 text-primaryDark tablet:text-fs-16-fw-400 dark:bg-primaryDark dark:text-primaryLight
const RootLayout = ({ children }: PropsWithChildren) => (
  <html
    lang='en'
    suppressHydrationWarning>
    <body className={manrope.className}>
      <Toaster toastOptions={{ duration: 1500 }} />
      {children}
    </body>
  </html>
)

export default RootLayout
