import type { Metadata } from 'next'
import type { PropsWithChildren } from 'react'

import { Manrope } from 'next/font/google'
import { SpeedInsights } from '@vercel/speed-insights/next'
import { Toaster } from 'react-hot-toast'

import './globals.css'

import { Providers } from './providers'

const manrope = Manrope({ subsets: ['latin'], weight: ['400', '500', '600'] })

export const metadata: Metadata = {
  title: 'Drink Master',
  description: 'Generated by create next app'
}

// bg-primaryLight text-fs-14-fw-400-lh-1.28 text-primaryDark tablet:text-fs-16-fw-400 dark:bg-primaryDark dark:text-primaryLight
const RootLayout = ({ children }: PropsWithChildren) => (
  <html
    // className="bg-black dark:bg-primaryLight"
    lang='en'
    suppressHydrationWarning>
    <body className={manrope.className}>
      <Toaster />
      <Providers>{children}</Providers>
      <SpeedInsights />
    </body>
  </html>
)

export default RootLayout
